[build]
  command = "npm install --force && npm run build"  # You might need to run 'npm run build' to build your Next.js application
  publish = ".next"  # Specify the output directory for your built files (default is .next)
